### ISSUE TITLE
How do I recompile the CV_bridge package with my own opencv version and python3

### ISSUE THREAD

**Issue by hanxiumeng** [BruceCanovas/supersurfel_fusion#2]
when I finished  catkin_make,,here is the log:
------------------------------------------------------------------
[ 96%] Linking CXX executable /home/robocup3d/catkin_ws/devel/lib/supersurfel_fusion/supersurfel_fusion_rgbd_benchmark_node
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_imgproc.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, not found (try using -rpath or -rpath-link)
[ 96%] Built target supersurfel_fusion_rgbd_benchmark_node
[100%] Linking CXX executable /home/robocup3d/catkin_ws/devel/lib/supersurfel_fusion/supersurfel_fusion_node
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_imgproc.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /opt/ros/melodic/lib/libcv_bridge.so, not found (try using -rpath or -rpath-link)
[100%] Built target supersurfel_fusion_node
--------------------------------------------------------------------------------------------
and then I run
 roslaunch supersurfel_fusion supersurfel_fusion_rgbd_benchmark.launch
here is the log:
/home/robocup3d/catkin_ws/devel/lib/supersurfel_fusion/supersurfel_fusion_rgbd_benchmark_node: error while loading shared libraries: libopencv_imgcodecs.so.3.2: cannot open shared object file: No such file or directory
-------------------------------------------------------------------------------------------------------
My own version of Opencv is 3.4.12, which is different from the ros version. By looking up the cause of the problem on the Internet, it was found that cV-Birdge needed to be recompiled, but no successful method was found. So I came to ask for your help again，thanks a lot

**Comment by hanxiumeng** [comment]
I figured out！

**Comment by abdulkarimatrash** [comment]
> I figured out！

can you please tell us how?
