### ISSUE TITLE
supersurfel_fusion/core/src/dense_registration.cu:141 : invalid configuration argument

### ISSUE THREAD

**Issue by hanxiumeng** [BruceCanovas/supersurfel_fusion#4]
When I run 
roslaunch  supersurfel_fusion supersurfel_fusion_rviz.launch 
with my own RGBD sensor(kinectV2),the  three topic information can be received correctly.
But there are no renderings of the reconstruction, and it will crash after running for a while. 
If you look at the output of the terminal, it seems to be the result of not having enough point matches. 
Is the RGBD information captured by the camera that caused the program to crash?
here is the log:-------------------------------------------------------------------------------------------------------------------
[ INFO] [1608195834.342321652]: rviz version 1.13.15
[ INFO] [1608195834.342344356]: compiled against Qt version 5.9.5
[ INFO] [1608195834.342349512]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1608195834.344416375]: Forcing OpenGl version 0.
[ INFO] [1608195834.850464300]: Stereo is NOT SUPPORTED
[ INFO] [1608195834.850502148]: OpenGl version: 4.6 (GLSL 4.6).
Camera info received
bestKey : 0
Total time = 34 ms
nb supersurfels: 864
stamp: 0
Max model size = 0.0856934 MB
Mean runtime = 34

 In ICP, number of matches is too small!   nb matches = 0
bestKey : 0
Total time = 4 ms
nb supersurfels: 0
stamp: 1
Max model size = 0.0856934 MB
Mean runtime = 19

bestKey : 0
Total time = 4 ms
nb supersurfels: 864
stamp: 2
Max model size = 0.0856934 MB
Mean runtime = 14

 In ICP, number of matches is too small!   nb matches = 0
bestKey : 0
Total time = 3 ms
nb supersurfels: 0
stamp: 3
Max model size = 0.0856934 MB
Mean runtime = 11.25

bestKey : 0
Total time = 11 ms
nb supersurfels: 864
stamp: 4
Max model size = 0.0856934 MB
Mean runtime = 11.2

 In ICP, number of matches is too small!   nb matches = 0
bestKey : 1
Total time = 9 ms
nb supersurfels: 0
stamp: 5
Max model size = 0.0856934 MB
Mean runtime = 10.8333

bestKey : 1
Total time = 9 ms
nb supersurfels: 864
stamp: 6
Max model size = 0.0856934 MB
Mean runtime = 10.5714

 In ICP, number of matches is too small!   nb matches = 0
bestKey : 1
Total time = 9 ms
nb supersurfels: 0
stamp: 7
Max model size = 0.0856934 MB
Mean runtime = 10.375

bestKey : 1
Total time = 9 ms
nb supersurfels: 864
stamp: 8
Max model size = 0.0856934 MB
Mean runtime = 10.2222
...
In ICP, number of matches is too small!   nb matches = 0
bestKey : 28
Total time = 9 ms
nb supersurfels: 0
stamp: 151
Max model size = 0.0856934 MB
Mean runtime = 9.17105

bestKey : 26
Loop closure detected
Not enough matches, nb matches = 0
cudaCheckError() failed at /home/slam/catkin_ws/src/supersurfel_fusion/core/src/dense_registration.cu:141 : invalid configuration argument

**Comment by BruceCanovas** [comment]
In the launch file have you set the right camera_info topic? Are your images registered? There is also a parameter called depth_scale that has been set to 1.0 in this launch file. If your depth is given in mm you need to change it to 0.001.

**Comment by hanxiumeng** [comment]
@BruceCanovas  yeah,it is the depth_scale problem

**Comment by hanxiumeng** [comment]
@BruceCanovas 
But here is a new question.
when I run roslaunch supersurfel_fusion supersurfel_fusion_rviz.launch,
sometimes it will fail, sometimes it will run seccessful . 
This error doesn't happen every time, it works out about once every three times,here is the log:
---------------------------------------------------------------------------------------------------------
[ INFO] [1608202697.094077174]: rviz version 1.13.15
[ INFO] [1608202697.094101372]: compiled against Qt version 5.9.5
[ INFO] [1608202697.094106631]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1608202697.096317335]: Forcing OpenGl version 0.
[ INFO] [1608202697.600992242]: Stereo is NOT SUPPORTED
[ INFO] [1608202697.601028604]: OpenGl version: 4.6 (GLSL 4.6).
Camera info received
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
--------------------------------------------------------------------------------------------
It says there's an illegal access to memory, 
and I guess there's something wrong with the code

**Comment by hanxiumeng** [comment]
oh,the other thing I forgot to mention is that enable_mod still fails in this node

**Comment by BruceCanovas** [comment]
For the problem with moving object detection I suggest we don't mix the two issues. 
For the rest, as I can't replicate those issues I would need more information in order to help you. Are you able to spot which part of the code is crashing?

**Comment by hanxiumeng** [comment]
> ## @BruceCanovas
> But here is a new question.
> when I run roslaunch supersurfel_fusion supersurfel_fusion_rviz.launch,
> sometimes it will fail, sometimes it will run seccessful .
> This error doesn't happen every time, it works out about once every three times,here is the log:
> ## [ INFO] [1608202697.094077174]: rviz version 1.13.15
> [ INFO] [1608202697.094101372]: compiled against Qt version 5.9.5
> [ INFO] [1608202697.094106631]: compiled against OGRE version 1.9.0 (Ghadamon)
> [ INFO] [1608202697.096317335]: Forcing OpenGl version 0.
> [ INFO] [1608202697.600992242]: Stereo is NOT SUPPORTED
> [ INFO] [1608202697.601028604]: OpenGl version: 4.6 (GLSL 4.6).
> Camera info received
> terminate called after throwing an instance of 'thrust::system::system_error'
> what(): CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered
> It says there's an illegal access to memory,
> and I guess there's something wrong with the code

---------------------------------------------------------------------------------
oh,I think I might be trying to figure out what the problem is, maybe it's the image resolution.
1920x1080 and 960x540 both work well every time,
but the raw rgb and depth images from the sensor (512x424) will fail sometimes.

**Comment by BruceCanovas** [comment]
For the record, image dimension are not hadcoded in the code (or if it is somewhere it's my mistake). I tested my code mostly with VGA resolution ie. 640x480.  Maybe there's a probleme with the grid and block dimension set for cuda kernels processing the images with this specific resolution.

**Comment by hanxiumeng** [comment]
yeah,I guess so. Thanks a lot !
