### ISSUE TITLE
[ Little advice ] put the datasets on other branch or repositories

### ISSUE THREAD

**Issue by ssmem** [BruceCanovas/supersurfel_fusion#5]
[ Little advice ] put the datasets on other branch or repositories.( or google drive, etc )
1.09 GB data on github is slowly to download.
( And also, I was interested in your oral works. And your reply is timely. Thank you! )

**Comment by BruceCanovas** [comment]
The oral presentation can be found on " https://www.iros2020.org/ondemand/ " (be aware of my poor english pronunciation, sorry for that^^) . The access is free and possible until the 24th of december. Good point for the datasets, I will consider it.
